baseURL = "https://www.exportcottage.com"
disqusShortname = ""
languageCode = "en-us"
languageName = "En"
paginate = "5"
theme = "persian"
title = "Export Cottage"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Contact"
url = "contact"
weight = 3
[[menu.main]]
name = "Brands"
url = "categories/nature/"
weight = 1
[[menu.main]]
name = "About"
url = "about"
weight = 2
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Export Cottage"
contact_form_action = "mailto: wecare@exportcottage.com"
copyright = "Designed & Developed By [Animis Global](http://animisglobal.com/)"
description = "This is meta description"
logo = "images/Export Cottage Logo Main (white).png"
search = false
[params.cookies]
enable = true
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
